# Header

# disable hexo highlight
highlight:
  enable: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# set archive pagination
archive_generator:
  per_page: 20
  yearly: true
  monthly: true
  daily: false
  order_by: -date

# set category pagination
category_generator:
  per_page: 20

tag_generator:
  per_page: 20

menu:
  首页: /
  归档: /archives/
  分类: /categories
  关于: /about

logo: 

favicon: /favicon.icon

# nav avatar
avatar: 